version: '3.7'
services:
  torrserve:
    image: ghcr.io/yourok/torrserver
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.dock
    container_name: torrserve
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TS_DONTKILL=true
      - TS_CONF_PATH=/opt/ts/config
      - TS_LOG_PATH=/opt/ts/log
      - TS_TORR_DIR=/opt/ts/torrents
      - TS_PORT=55510
    ports:
      - "127.0.0.0:55510:55510"
    volumes:
      - config:/opt/ts/config
      - log:/opt/ts/log
      - torrents:/opt/ts/torrents
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:55510"]
      interval: 1m30s
      timeout: 10s
      retries: 3

    networks:
      wg_net:
        ipv4_address: 172.16.50.2

volumes:
  config:
  log:
  torrents:

networks:
  wg_net:
    external: true
