FROM ghcr.io/yourok/torrserver:latest

RUN apk add curl && apk add bash && apk add iptables

# drop all IP's except 172.16.50.3

RUN iptables -I INPUT -p tcp ! -s 172.16.50.3 --dport 55510 -j DROP

ENTRYPOINT ["docker-entrypoint.sh"]